import { Theme } from "../styles/theme.slint";

export component StatusBar inherits Rectangle {
    in property <string> item-count: "0 itens";
    in property <string> selected-info: "";
    in property <string> disk-space: "";
    in property <string> sort-info: "";
    in property <string> search-info: "";
    callback toggle-metrics();

    height: 26px;
    background: Theme.surface;

    // Separador superior
    Rectangle {
        y: 0px;
        height: 1px;
        width: parent.width;
        background: Theme.border;
    }

    HorizontalLayout {
        padding-left: Theme.padding-large;
        padding-right: Theme.padding-large;
        spacing: 16px;

        Text {
            text: item-count;
            color: Theme.text-secondary;
            font-size: Theme.font-small;
            vertical-alignment: center;
        }

        Rectangle {
            width: 1px;
            height: 14px;
            background: Theme.border;
            vertical-stretch: 0;
        }

        Text {
            text: selected-info != "" ? "Selecionado: " + selected-info : "";
            color: Theme.text-secondary;
            font-size: Theme.font-small;
            vertical-alignment: center;
            overflow: elide;
        }

        Rectangle {
            width: sort-info != "" ? 1px : 0px;
            height: 14px;
            background: Theme.border;
            vertical-stretch: 0;
            visible: sort-info != "";
        }

        Text {
            text: sort-info;
            color: Theme.text-secondary;
            font-size: Theme.font-small;
            vertical-alignment: center;
            visible: sort-info != "";
        }

        Rectangle {
            width: search-info != "" ? 1px : 0px;
            height: 14px;
            background: Theme.border;
            vertical-stretch: 0;
            visible: search-info != "";
        }

        Text {
            text: search-info;
            color: Theme.text-secondary;
            font-size: Theme.font-small;
            vertical-alignment: center;
            visible: search-info != "";
        }

        Rectangle { horizontal-stretch: 1; }

        TouchArea {
            width: btn_text.preferred-width;
            visible: sort-info != "" || search-info != "";
            clicked => { root.toggle-metrics(); }
            btn_text := Text {
                text: "[+] Mais info";
                color: Theme.primary;
                font-size: Theme.font-small;
                vertical-alignment: center;
            }
        }

        Text {
            text: disk-space;
            color: Theme.text-secondary;
            font-size: Theme.font-small;
            vertical-alignment: center;
        }
    }
}
